[package]
name = "domain"
version = "0.1.0"
authors = ["Phil White <phil.white@creditsafe.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
