[package]
name = "tic_tac_toe"
version = "0.1.0"
authors = ["Phil White"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstest = "0.10.0"
